<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
    // var num=18;
    // const promise = new Promise ((resolve , reject)=>{
    //     if ( num>=18){
    //         resolve("Valid fo vote")
    //     }
    //     else {
    //         reject("Not valid for vote")
    //     }
    // })
    // promise 
    // .then((res)=>{console.log( "Resolved:" , res)}) // resolve is going in then and rejecat in catch
    // .catch((err)=>{console.log( "Error occured:" , err)})



    //async and await

    async function execute(){
        try {
            const res= await promise;
            console.log(res)
        }
        catch (error){
            console.log("Error Occured", error)
        }
    }


    </script>
</body>
</html>